STRINGS.NAMES.ZX_GRANARY_VEGGIE = "蔬菜仓"
STRINGS.RECIPE_DESC.ZX_GRANARY_VEGGIE = "它能存很多蔬菜！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZX_GRANARY_VEGGIE = "里面的蔬菜很新鲜!"

STRINGS.NAMES.ZX_GRANARY_MEAT = "肉仓"
STRINGS.RECIPE_DESC.ZX_GRANARY_MEAT = "它能存很多肉！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZX_GRANARY_MEAT = "每个人都要吃上肉蛋奶!"

-- 花1
STRINGS.NAMES.ZX_FLOWER_1 = "小雏菊花丛"
STRINGS.RECIPE_DESC.ZX_FLOWER_1 = "漂亮的黄色小花!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZX_FLOWER_1 = "真漂亮!"


-- 老奶奶晾肉架
STRINGS.NAMES.MEATRACK_HERMIT = "隐士晾肉架"
STRINGS.RECIPE_DESC.MEATRACK_HERMIT = "寄居蟹奶奶建的!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEATRACK_HERMIT = "挂上肉更好看!"

-- 老奶奶蜂箱
STRINGS.NAMES.BEEBOX_HERMIT = "隐士蜂箱"
STRINGS.RECIPE_DESC.BEEBOX_HERMIT = "寄居蟹奶奶建的蜂箱!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEBOX_HERMIT = "好多小蜜蜂!"