
---- 动作相关
STRINGS.ZXACTION = {
	ZXSHOPOPEN = "选择模式",
	ZXHATCH = "孵化",
	ZXADDFOOD = "添加饲料",
	ZXFARMHARVEST = "收获产品",
	UPGRADE = "升级",
	ACCELERATE = "加速",
}

STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.ZXHATCH = {
	NO_HOST = "附近没有可用的农场！",
	NO_FEEDER = "附近没有可用的饲料盆！",
	BUSY = "一个新生命正在孵化中!",
	NO_SPACE = "农场已经挤满小动物了!"
}
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.ZXADDFOOD = {
	FULL = "饲料多的快溢出来了！",
}
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.ZXFARMHARVEST = {
	EMPTY = "这里面空空如也！",
}
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.ZXUPGRADE = {
	MAX = "已经是最高等级了!",
	INVALID_ITEM = "换个材料试试吧!"
}


STRINGS.ZX_SKIN_PAGE_TITLE = "建家党小店"
STRINGS.ZX_SKIN_PAGE_NOTICE = "神秘的获取方式(群号600710976)..."
STRINGS.ZX_SKIN_HAS = "已拥有"
STRINGS.ZX_SKIN_NOT_HAS = "未拥有"
STRINGS.ZXDESTROY = "销毁"
STRINGS.ZXUSE = "使用"
STRINGS.ZX_UPGRADE_SUCCESS = "升级成功!"
STRINGS.ZX_ACCELERATE_SUCCESS = "加足马力生产!"