STRINGS.NAMES.ZX_GRANARY_VEGGIE = "蔬菜仓"
STRINGS.RECIPE_DESC.ZX_GRANARY_VEGGIE = "它能存很多蔬菜！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZX_GRANARY_VEGGIE = "里面的蔬菜很新鲜!"

STRINGS.NAMES.ZX_GRANARY_MEAT = "肉仓"
STRINGS.RECIPE_DESC.ZX_GRANARY_MEAT = "它能存很多肉！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZX_GRANARY_MEAT = "每个人都要吃上肉蛋奶!"