STRINGS.NAMES.ZX_GRANARY_VEGGIE = "Vegetable granary"
STRINGS.RECIPE_DESC.ZX_GRANARY_VEGGIE = "It can store a lot of vegetables!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZX_GRANARY_VEGGIE = "The vegetables inside are fresh!"

STRINGS.NAMES.ZX_GRANARY_MEAT = "Meat granary"
STRINGS.RECIPE_DESC.ZX_GRANARY_MEAT = "It can store a lot of meat!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZX_GRANARY_MEAT = "Everyone has to eat meat, eggs and milk!"

-- 花1
STRINGS.NAMES.ZX_FLOWER_1 = "Daisy bushes"
STRINGS.RECIPE_DESC.ZX_FLOWER_1 = "Small yellow flowers"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZX_FLOWER_1 = "so beautiful!"
-- 花2
STRINGS.NAMES.ZX_FLOWER_1 = "Oxalis"
STRINGS.RECIPE_DESC.ZX_FLOWER_1 = "Pourple represents nobility!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZX_FLOWER_1 = "so beautiful!"

-- 老奶奶晾肉架
STRINGS.NAMES.MEATRACK_HERMIT = "Meatrack hermit"
STRINGS.RECIPE_DESC.MEATRACK_HERMIT = "Built by hermit crab grandma!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEATRACK_HERMIT = "It looks better to hang the meat!"
-- 老奶奶蜂箱
STRINGS.NAMES.BEEBOX_HERMIT = "BeeBox hermit"
STRINGS.RECIPE_DESC.BEEBOX_HERMIT = "Built by hermit crab grandma!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEBOX_HERMIT = "so many bees!"